version: 2

project_name: terraform-provider-garage

builds:
  - id: provider
    main: .
    binary: terraform-provider-garage_{{.Version}}
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - id: default
    builds:
      - provider
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - terraform-registry-manifest.json
  # Also upload raw binaries (matching Grafana provider pattern for direct downloads)
  - id: binaries
    builds:
      - provider
    format: binary
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

signs:
  - artifacts: checksum
    args:
      # if you are using this is a GitHub action or some other automated pipeline, you
      # need to pass the batch flag to indicate its not interactive.
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  mode: replace
  name_template: "v{{ .Version }}"
  header: |
    ## Terraform Provider Garage {{ .Version }}

    See [CHANGELOG.md](CHANGELOG.md) for details.
  footer: |
    ## Installation

    ```hcl
    terraform {
      required_providers {
        garage = {
          source  = "d0ugal/garage"
          version = "{{ .Version }}"
        }
      }
    }
    ```
