version: 2

project_name: terraform-provider-garage

before:
  hooks:
    # Ensure go.mod is tidy before building
    - go mod tidy

builds:
  - id: provider
    main: .
    binary: '{{ .ProjectName }}_v{{ .Version }}'
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

archives:
  - id: default
    builds:
      - provider
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - terraform-registry-manifest.json

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

signs:
  - artifacts: checksum
    args:
      # if you are using this is a GitHub action or some other automated pipeline, you
      # need to pass the batch flag and pinentry-mode to indicate its not interactive.
      - "--batch"
      - "--yes"
      - "--pinentry-mode"
      - "loopback"
      - "--passphrase"
      - "{{ .Env.GPG_PASSPHRASE }}"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  name_template: "v{{ .Version }}"
  # Create as draft first (can be published manually or via API)
  # Remove draft: true if you want releases published immediately
  draft: false
  header: |
    ## Terraform Provider Garage {{ .Version }}

    See [CHANGELOG.md](CHANGELOG.md) for details.
  footer: |
    ## Installation

    ```hcl
    terraform {
      required_providers {
        garage = {
          source  = "d0ugal/garage"
          version = "{{ .Version }}"
        }
      }
    }
    ```

changelog:
  disable: true
