name: Release Please

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      with:
        fetch-depth: 0
        token: ${{ secrets.RELEASE_TOKEN }}

    - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5
      id: release_please
      with:
        release-type: go
        path: .
        token: ${{ secrets.RELEASE_TOKEN }}
        default-branch: main
        fork: false
